export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A giant snail carrying a city on its back, digital art",
  "A neon-lit cyberpunk street market bustling with robotic vendors, digital art",
  "A watercolor painting of a giraffe wearing a space helmet and floating in zero gravity",
  "A steampunk airship soaring above a Victorian cityscape at sunset",
  "An abstract painting of a dolphin swimming through a sky filled with colorful clouds",
  "A robotic hummingbird pollinating a flower made of metal and glass, digital art",
  "A serene forest scene with trees made of crystal and a river of liquid gold, digital art",
  "A whimsical illustration of a dragon serving tea to a group of fairies in a magical forest",
  "A black-and-white photograph of a vintage typewriter with keys shaped like tiny planets",
  "A digital painting of a mermaid reading a book in an underwater library",
  "A retro-futuristic diner on Mars, with astronauts enjoying milkshakes, digital art",
  "A fantastical landscape with floating islands connected by rainbow bridges, digital art",
  "An oil painting of a cat dressed as a Renaissance nobleman, complete with a ruffled collar",
  "A detailed sketch of a time-traveling pirate ship sailing through the clouds",
  "A high-tech cityscape where buildings are made of giant crystals, digital art",
  "A playful scene of unicorns playing soccer in a meadow, digital art",
  "A 3D render of a whimsical clock tower covered in vines and flowers",
  "A digital painting of a samurai fighting a dragon in a neon-lit alleyway",
  "A fantasy illustration of a knight riding a dragon through a starry night sky",
  "A surreal image of a tree with branches made of candy canes and leaves made of gumdrops",
  "A cybernetic phoenix rising from a cityscape of futuristic skyscrapers, digital art",
  "An astronaut exploring an alien jungle filled with bioluminescent plants, digital art",
  "A retro-futuristic robot serving coffee in a cozy 1950s-style cafe, digital art",
  "A whimsical painting of a rabbit wearing a top hat and monocle, having tea with a hedgehog",
  "A 3D render of a futuristic floating garden with holographic flowers",
  "A mystical forest scene where the trees have faces and tell stories to passersby, digital art",
  "A steam-powered robot butler serving breakfast in a lavish Victorian dining room",
  "A neon-colored jellyfish swimming through a city underwater, digital art",
  "A digital painting of a giant panda meditating on top of a mountain with cherry blossoms",
  "A surreal scene of a castle floating in the sky, tethered to the ground by giant chains",
  "An oil painting of a fox dressed in a 1920s flapper dress, dancing at a jazz club",
  "A 3D render of an alien landscape with towering rock formations and multiple moons in the sky",
  "A whimsical scene of a mouse knight fighting a dragonfly dragon, digital art",
  "A vibrant street art mural of a chameleon blending into a graffiti-covered wall",
  "A digital painting of a futuristic city where people travel by floating bubbles",
  "A fantasy illustration of a wizard casting a spell in a dark, enchanted forest",
  "A steampunk-inspired illustration of a hot air balloon festival with mechanical balloons",
  "A cyberpunk cityscape with flying cars and towering neon skyscrapers, digital art",
  "A watercolor painting of a peaceful village nestled in the branches of a giant tree",
  "A whimsical drawing of a turtle with a city on its shell, slowly moving through a desert",
  "A digital painting of a fairy tale castle made entirely of candy and sweets",
  "A surreal portrait of a woman with flowers growing out of her hair and butterflies around her, digital art",
  "A fantasy landscape with a river of stars flowing through a forest of glowing trees",
  "A digital painting of a futuristic robot gardener tending to a garden of metallic flowers",
  "A whimsical scene of penguins having a beach party under the northern lights, digital art",
  "A 3D render of a fantasy dragon curled up on a pile of glowing treasure",
  "A vibrant digital painting of an enchanted library with floating books and magical creatures",
  "A surreal landscape of mountains that look like they are made of folded paper",
  "A detailed illustration of a mermaid city deep underwater, illuminated by bioluminescent corals",
  "A whimsical drawing of a cat exploring a galaxy in a cardboard spaceship",
  "A digital painting of a majestic stag standing in a forest of towering mushrooms",
  "A fantasy scene of a phoenix rising from the ashes in a moonlit clearing, digital art",
  "A steampunk-inspired illustration of a time-traveling train chugging through the clouds",
  "A digital painting of a serene alien planet with floating islands and crystal-clear lakes",
  "A whimsical scene of a family of owls living in a cozy treehouse, digital art",
  "A 3D render of a futuristic city with transparent skyscrapers and flying vehicles",
  "A surreal image of a clock melting over a desert landscape, inspired by Salvador Dalí",
  "A vibrant digital painting of a marketplace on an alien planet, bustling with strange creatures",
  "A fantasy illustration of a dragon and a unicorn having a picnic in a magical meadow",
  "A detailed sketch of a futuristic spaceship docked at a space station orbiting Earth",
  "A whimsical drawing of a mouse family living in a cozy shoe house in the forest",
  "A digital painting of a robot painter creating a masterpiece in a futuristic art studio",
  "A serene landscape of a beach with sand made of stardust and waves of liquid silver",
  "A fantasy scene of a knight and a dragon forging an alliance in a mystical cave, digital art",
  "A steampunk-inspired illustration of a clockwork city with gears and cogs in motion",
  "A vibrant digital painting of a carnival in space, with rides and attractions floating in zero gravity",
  "A whimsical scene of a frog prince sitting on a lily pad, holding a tiny scepter, digital art",
  "A 3D render of a futuristic garden with bioluminescent plants and robotic gardeners",
  "A surreal image of a city where the buildings are made of giant books, digital art",
  "A fantasy illustration of a mermaid riding a seahorse through an underwater kingdom",
  "A detailed sketch of a dragon perched on top of a skyscraper, overlooking a modern city",
  "A whimsical drawing of a fox and a hedgehog having a tea party in a magical forest",
  "A digital painting of a futuristic city with flying robots and holographic billboards",
  "A serene landscape of a mountain range with peaks that glow in the dark, digital art",
  "A fantasy scene of a wizard and a dragon casting spells in a mystical duel, digital art",
  "A steampunk-inspired illustration of a mechanical bird soaring through the clouds",
  "A vibrant digital painting of an enchanted garden with flowers that light up at night",
  "A whimsical scene of a cat and a dog exploring a fantastical world together, digital art",
  "A 3D render of a futuristic city with floating walkways and high-tech architecture",
  "A surreal image of a desert with dunes made of colorful sand, digital art",
  "A fantasy illustration of a knight riding a dragon through a fiery landscape",
  "A detailed sketch of a steampunk airship with intricate gears and cogs",
  "A whimsical drawing of a rabbit riding a bicycle through a magical forest",
  "A digital painting of a futuristic city with glowing neon signs and bustling streets",
  "A serene landscape of a lake with water that reflects the colors of the rainbow, digital art",
  "A fantasy scene of a dragon and a unicorn standing together in a mystical meadow, digital art",
  "A steampunk-inspired illustration of a time-traveling airship with Victorian-era passengers",
  "A vibrant digital painting of a bustling marketplace in a futuristic city",
  "A whimsical scene of a frog prince and a fairy princess having a picnic in a magical forest, digital art",
  "A 3D render of a futuristic city with transparent buildings and flying cars",
  "A surreal image of a forest with trees that have leaves made of glass, digital art",
  "A fantasy illustration of a knight and a dragon exploring a mystical cave",
  "A detailed sketch of a steampunk airship with intricate gears and cogs, soaring through the sky",
  "A whimsical drawing of a rabbit riding a bicycle through a magical forest, digital art",
  "A digital painting of a futuristic city with glowing neon signs and bustling streets",
  "A serene landscape of a lake with water that reflects the colors of the rainbow, digital art",
  "A fantasy scene of a dragon and a unicorn standing together in a mystical meadow, digital art",
  "A steampunk-inspired illustration of a time-traveling airship with Victorian-era passengers",
  "A vibrant digital painting of a bustling marketplace in a futuristic city",
  "A whimsical scene of a frog prince and a fairy princess having a picnic in a magical forest, digital art",
  "A 3D render of a futuristic city with transparent buildings and flying cars",
  "A floating island with a medieval castle and a cascading waterfall, digital art",
  "A dreamlike scene of an elephant walking on water under a starry sky, digital art",
  "A robotic dragon breathing fire in a futuristic cityscape, digital art",
  "A mermaid singing to the moon on a rocky shore, surrounded by glowing fish, digital art",
  "A surreal landscape of giant mushrooms with tiny cities on top, digital art",
  "A vintage car driving through a tunnel of cherry blossoms, digital art",
  "A steampunk airship docked at a floating city in the clouds, digital art",
  "A fairy riding a butterfly through a magical forest, digital art",
  "An ancient tree with a door leading to another dimension, digital art",
  "A futuristic robot chef preparing a gourmet meal in a high-tech kitchen, digital art",
  "A mystical stag with glowing antlers standing in a moonlit glade, digital art",
  "A cyberpunk city with neon signs and flying drones, digital art",
  "A giant octopus wrapping its tentacles around a skyscraper, digital art",
  "A fairy tale castle made of ice and snow, sparkling in the sunlight, digital art",
  "A majestic lion wearing a golden crown, sitting on a throne in a lush jungle, digital art",
  "A futuristic spaceship flying through a nebula of vibrant colors, digital art",
  "A magical library with books that float and glow, digital art",
  "A scene of dinosaurs coexisting with futuristic humans in a vibrant city, digital art",
  "A whimsical treehouse village high in the treetops, digital art",
  "A surreal beach with sand that glows in the dark and bioluminescent waves, digital art",
  "A knight in shining armor riding a dragon through a portal to another world, digital art",
  "A neon-lit underwater city inhabited by mermaids and sea creatures, digital art",
  "A giant clock tower with gears exposed and glowing with inner light, digital art",
  "A peaceful scene of a panda meditating in a bamboo forest under a full moon, digital art",
  "A whimsical scene of a hot air balloon festival in a fantasy world, digital art",
  "A surreal landscape with floating rocks and waterfalls flowing upwards, digital art",
  "A fantasy warrior battling a giant serpent in an ancient ruin, digital art",
  "A steampunk-inspired mechanical owl with glowing eyes, perched on a Victorian lamppost, digital art",
  "A futuristic city with floating gardens and transparent buildings, digital art",
  "A mystical wolf howling at a crescent moon in a starry sky, digital art",
  "A colorful parade of mythical creatures marching through a fantasy city, digital art",
  "A serene garden with a fountain of glowing water and bioluminescent plants, digital art",
  "A surreal dreamscape with melting clocks and floating islands, digital art",
  "A dragon curled around a treasure chest in a cavern filled with glowing crystals, digital art",
  "A futuristic monorail gliding through a city of glass and steel, digital art",
  "A whimsical scene of a circus in the clouds with acrobats and flying animals, digital art",
  "A cybernetic tiger prowling through a neon jungle, digital art",
  "A magical carousel with unicorns and dragons instead of horses, digital art",
  "A surreal portrait of a woman with galaxies in her eyes and constellations in her hair, digital art",
  "A steampunk laboratory with bubbling potions and intricate machinery, digital art",
  "A fantasy landscape with a bridge made of rainbows and mountains of cotton candy, digital art",
  "A futuristic athlete running on a track that spirals through the sky, digital art",
  "A serene scene of a koi pond with glowing fish and floating lanterns, digital art",
  "A whimsical depiction of a festival on a floating island with fireworks and lanterns, digital art",
  "A cyberpunk detective investigating a mystery in a rain-soaked city, digital art",
  "A surreal underwater scene with giant jellyfish and sunken treasure, digital art",
  "A majestic phoenix rising from the ashes in a fiery display, digital art",
  "A futuristic library with holographic books and robotic librarians, digital art",
  "A whimsical scene of a tea party with talking animals and floating teapots, digital art",
  "A fantasy warrior riding a giant eagle through a stormy sky, digital art",
];


export const randomNames = [
  'Olivia Thompson',
  'Liam Johnson',
  'Emma Williams',
  'Noah Brown',
  'Ava Jones',
  'Elijah Garcia',
  'Sophia Martinez',
  'Lucas Miller',
  'Isabella Davis',
  'Mason Rodriguez',
  'Mia Hernandez',
  'Logan Lopez',
  'Charlotte Wilson',
  'Ethan Anderson',
  'Amelia Thomas',
  'James Moore',
  'Harper Taylor',
  'Alexander Jackson',
  'Evelyn White',
  'Benjamin Harris',
  'Abigail Martin',
  'Henry Clark',
  'Ella Lewis',
  'Aiden Robinson',
  'Scarlett Walker',
  'Samuel Perez',
  'Grace Hall',
  'Sebastian Young',
  'Victoria Allen',
  'Jack King',
  'Aria Scott',
  'Owen Green',
  'Lily Adams',
  'Wyatt Baker',
  'Chloe Gonzalez',
  'Daniel Nelson',
  'Zoe Carter',
  'Matthew Mitchell',
  'Riley Perez',
  'Jackson Roberts',
  'Nora Turner',
  'Luke Phillips',
  'Hannah Campbell',
  'Gabriel Parker',
  'Layla Evans',
  'Julian Edwards',
  'Aubrey Collins',
  'David Stewart',
  'Ellie Sanchez',
  'Anthony Morris',
  'Penelope Rogers',
  'Christopher Reed',
  'Avery Cook',
  'Joshua Morgan',
  'Mila Bell',
  'Andrew Murphy',
  'Paisley Cooper',
  'Lincoln Rivera',
  'Savannah Bailey',
  'Joseph Gonzalez',
  'Leah Hayes',
  'Carter Gray',
  'Eleanor Jenkins',
  'Isaac Patterson',
  'Stella Hughes',
  'Dylan Washington',
  'Zoey Howard',
  'Grayson Brooks',
  'Natalie Ross',
  'Levi Ward',
  'Violet Simmons',
  'Mateo Peterson',
  'Hazel Foster',
  'Asher Powell',
  'Aurora Long',
  'Hudson Butler',
  'Addison Bryant',
  'Nathan Hill',
  'Lucy Griffin',
  'Leo Fisher',
  'Brooklyn Russell',
  'Ryan Bennett',
  'Willow Alexander',
  'Jaxon Barnes',
  'Emilia Webb',
  'Caleb Wheeler',
  'Luna Chapman',
  'Christian Edwards',
  'Ivy Medina',
  'Hunter Black',
  'Ariana Stephens',
  'Connor Myers',
  'Madelyn Kelley',
  'Aaron Elliott',
  'Piper Lawson',
  'Eli Hamilton',
  'Claire Romero',
  'Isaiah Fletcher',
  'Savannah McDonald',
  'Thomas Holland',
  'Maya Austin',
  'Charles Graham',
  'Isla Burke',
  'Josiah Ramirez',
  'Ruby Wallace',
];
